language: ruby
services:
- docker
script:
- make test
after_script:
- make clean
notifications:
  slack:
    rooms:
      secure: kERSGwhnf1a9EsLJa/TheYQ2QNqh9PbpTD4iRyMq1zYAhu78m+hIpmrycVnOSF5yCVsyHG9S9NoDIOeGrgAP+JyFMUNlt4GyxDchEuBvbzoZojB02eCz1+GboZggjwNlGGQhzLDq+hw022sNucUJW8SL3rfMMrqzgGP6+0rYtvEAC0Gqd8ETyOeDmk9YhV7/1n/BhQWRe614a4CtVf4rfXWlY3Xv4fbtF2MBXIkcVghBgQP8D3fczDK+pOtC3VhyUdfu19WVe+9hvTG7Uon90zUCv1Z09sknyn/EZkYUQxY6i5P9OpIB5JzH+1nBXRbr1zxINBdqdEhAfGzS6nTIVBtHzgBoHmGuXgbJhADxQDJlP2MwarLPTdaP1Mt6QtNyDoYcqjtUM79c8rh7RKupKn9peuc6eizzDk20SWhD8FAWZQToVY6WhZUi0wwwtGXQTAeFCRw7H+46MOtMqvE5/Vr6FaQaSRtPGy8eAqZYFL2rYxiNxWELnlhyaB18/McBRgBViQLUlcGBWT6xfk+/M2E498XERHXQtTay65dEeVuBck5VYcg/WGV4De48nAE5MdckcY6YwG+0pPW3E3+JpCUly4x5CQVRimWTrOX6K6dBgsLXnpFP6H80296ZvUfSAN9SHdNWxFTSNv48j94WtE0lif/T690M9Ueevovk8gs=
