language: ruby
services:
- docker
script:
- make test
after_script:
- make clean
notifications:
  slack:
    rooms:
      secure: H/2omsXf2ke0wmmTDQOFwSO9M0Orx+rzKbdBb/B5ZnkcKbplhDIZrIJmTIpozQ8f+pD6Qk8HZmw/qrup+uRHA0SWOIH3U0kr/k7ARnjbQjI6lrQW+NQEawsjGo0hk6ug6zWO1aTohjriuOkbPIyH0nF7i599eo1YkFZXJ3I5Hd61WTEnjiD6DgPxqCTO0RuBUCP1OzZcgXJV7QD64uqYYVCOUpPEKfFQWZhEQ1TItMq/8MV8Hns9htw1aRnw0pOojCZzp6arpFGsnKprf34+egW7hEFxeue2tg9/xsUCiQi/95iSLqa6dX4ZGYq+u+5bfFyDbh4N4dxe+nne+THQ9tPB8fUWO/eezoTzpQgaczHdTAaHqG7aJk08KiGscVBTtuX5W/Wly4Cjt1c/yYVfiIzEwO6T0cYMeLkKSkgDUtWEF72nu96cw4zz/8xW/7oO+zNOIKQjwNPIym32hW9h9InCDvlIc2KAiP7971IvSGMgRwQX0PR8432kR66G8Es7ntMBrN+j+B+PynRJiIHC8rD6qhhzh4B0EQ1TC0YxZP13p2pub2UEjFSUd1i8rDOwKieK1H8zHspWghrAnir57APCxKPtVnK0NVFK6bLJ7at+Dc8hrc2Y7KK6O12yAeQAH7GwQ+11uI34mKksEglPGMg4Oym8FA6etmuCut7HgTY=
