language: ruby
services:
- docker
script:
- make test
after_script:
- make clean
notifications:
  slack:
    rooms:
      secure: D706a6TQ4eIw1HfoYF1nDzO9RlZams1VZFeMc42iASfXCQPZWqVKNd6Dq8yFZA5rPlVou7KTeuulEvN/e2L3gTAziu2y/ARGe9h2a/TI/zqsw31NZb6FB5xRd/5q4fJU/k5MzudkpzOWanpKBon4FaBJJ4pjZdIp7WrljnfNE/6mCFdWLLdcnRIReGBuSzWYgxnNvcTdUql3o7gYHtj0XbRiyuHPW1XnwYmZPeVYLrzhg083zG3Q6OBDzoJAusOWoiaP6ow6P42lhGdbgtEpCdh7g89b3tzvkMxI6j1KX4dHAdbwjLBGXdh9G6iLuNWbXm3F4e+TCLw0vp1mf1XMV9O1l52Te2iK0uu0cGup84owL4JgPF+V/HariGB+eSFaW2IU+SC8e9VHI2Si9ehfX9/JNM0z6czP0aPINj0lKvNLSEoBU34CWwD7rwlZp/TlDht6RaxO4C8qEvG0TySxC5iJX8Icj/xN5mNLBvL5CzeEpPMTLMK8i8eyTn26pOPaBQE6oG5fZxd2dvdUlcV/UwknSIfbLbmYQBHPNscxxzbaxzQaR70V/8EO6Fb2/J53K4R7BxSONqt+YQMxdMUch1gKsW4JY2ler8D0ErrVG71Wj62+csu6o7bAS/s0UN0GvMJj2cpH28NBzbg3bAq0B7DLYvLdP37fpFxWmq03RW8=
