language: ruby
services:
  - docker
script:
  - make test
after_script:
  - make clean
notifications:
  slack:
    rooms:
      secure: TrelelwuvICTJElrjjhG8Tu57rtFGIVPYyy9E+U9sEKM4qOIO830cA5mR0b9YfyHsG8AGlayji7t2MXbXVjVqOY/5Vs6edDSMxzK2zM07ShvMFiwrzi8SI1jhmgMaWd2gg4HPIRMWOl4l5nnvqf0CfnDWHKJjixnUe5W50TqfZUgpACxb6skvuka7mePZPe7VMaTwACd+vcAxwjWEZCyYy0YgmxPZ+lYRFPDSZdmnPrDeTaxGw4yBWLN1OUkgad21TYdnWxzTVcbUlZn9nOyJKC0LlK13odWTjUj53u9sdu71Arwm96EPqxLzNbeje/C3cuxNA+Tw5V3GKCdzW5l/jRrw5flIMjicfkGpB3G1nK5/Gkz2Nl7+i6defY6bwgGtTRaTAPFbmBRnYRjd/e+lHfxh4AcMHmGJ6d/sIZW8j09e/sYWiT6lqu51cuTesvzPFVftMJsF33JQIGWJB4KF7OT2eem/zlSNt+FNmV4dRontm+x2zz8upyeKypIsxEUZtlZ8N3ShbU8zOXXF/oz9EdECMvyoBtB0pXeeLey4OtR/XYyGvi4Zxz7mOZI8OBqOVb9jVDe4oAfw8F0dGqtv0cMgNB2adEKmzlL8yUX1ggni4BiWGLfWBhfMEn+clKZ4fKpVvyOJ1t51Domy0EumjdASfyzgyFRM8nGU4kttE0=
