language: ruby
services:
- docker
script:
- make test
after_script:
- make clean
notifications:
  slack:
    rooms:
      secure: H93IkMEUeH9lTmi45n1Tkaw8XA3nCpr4/F+Jqai3IHsoQjUo6dEtb3BKUvFIIk3I53zHekzcdUdD9Kw48ESorQozja4yXjvLn1S6Z1aQGhQeExqVu7G5/2XJI6mS1dUTP4+RcveemRZrjSs1BVdyzvyo3rFSU2u2LFjrAWajN6Cyv0tikSQWpUPyIGdCGx7aXaV/5ya4IxC5DVngM6EH4plyGb1k71oEV/7uj2Yc70ZlANi7ZFUTuLJIKMphoMaMW9zGortiAUPLySgXnPU3CsMRxtOvQ8tZsFTUO1x2GOkgeQ3sSBKHDTlGtxBvcvh4J4UDJ4fyDXyg4AMdNlhlYM42hH6UF+XfeUAzwTPMe8FcKNg2z/I5fq7SiL0d89MZgKRJwXS2xBc+A+2E6lsM7bl8F92eqUdtxZrDbMvvz1MtSqOCOjU/ZtQGDJewehi0j9dHUxDNa+KErdKALbCvOBHIyXSPkANM8zfWUhWeOCmDDSdOoL2OOg3iptR6MmH0GKAk623OkN7BSlOvjASHnQKbXjTIH3ECTTvdeYtaluVU5jfO9SrDJ9qcxhNT/bgvONDeiaa7trIG5fpZSRBUUuIS1qul3zII85JDIAkX4TfGyUeGJSISaVnW4QbI311QBhnpj/FWIcPTpyiLnlltY5XRM13kZO4ezBAMeP6nKEU=
